version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fintransact-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fintransact
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: fintransact-rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  core-api:
    build: ./backend/core-api
    container_name: fintransact-core-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fintransact
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - postgres
      - rabbitmq

  notification-service:
    build: ./backend/notification-service
    container_name: fintransact-notification-service
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq

  frontend:
    build: ./frontend
    container_name: fintransact-frontend
    ports:
      - "4200:80"
    depends_on:
      - core-api

volumes:
  postgres_data:
